version: "3.9"
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - ./chroma_data:/chroma/.chroma/index

  python-app:
    build: ./app
    container_name: support-bot
    restart: unless-stopped
    depends_on:
      - chromadb
    volumes:
      - ./app:/app
    command: ["python", "main.py"]
