version: "3.9"

services:
  chromadb:
    image: chromadb/chroma:0.5.0
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/chroma_db

  supportbot:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - chromadb
    ports:
      - "9000:9000"
    volumes:
      - ./chroma_db:/app/chroma_db  